added notebook for uploading model data
ADAQ-AQI/cap-notebooks pull request #15
Opened 2022-12-07 11:16 UTC by tomw66

I've added a notebook to help with uploading AQUM model data, similar to the one for MOASA flight data.

2023-01-09 12:11 UTC, corinnebosley requested changes
One or two small changes in the text, with an option for using a dummy credential if possible.

Other than that, looks like a lovely notebook.  Nice work.

2023-01-09 12:11 UTC, corinnebosley commented on helper-funcs/uploading_AQUM_data.ipynb
> +   ]
Is there something we can use here for access credentials, just to demonstrate the process, like a dummy log-in or something?

If not, this is fine, but it means that I can't actually run this cell or anything following it as I don't have access.  I can of course run the `access_datastore` notebook to get them (I assume), so I'll do that now.

2023-01-09 12:11 UTC, corinnebosley commented on helper-funcs/uploading_AQUM_data.ipynb
> +   ]
I like the clarity here.

2023-01-09 15:35 UTC, tomw66 commented on helper-funcs/uploading_AQUM_data.ipynb
> +   ]
I don't think so, would maybe be a security issue for jasmin. It's probably a good idea for you to get credentials set up anyway, though it is fiddly so let me know if you need help!

2023-01-10 07:41 UTC, corinnebosley approved these changes

2023-01-10 07:43 UTC, corinnebosley commented on helper-funcs/uploading_AQUM_data.ipynb
> +   ]
You're not wrong.  I'll get my shizzle together and get access to JASMIN myself.

2023-01-10 07:45 UTC, corinnebosley commented
Nice notebook Tom.  Merge when ready.

2023-01-10 09:41 UTC, merged